### ISSUE TITLE
Strongswan bbappend version does not match meta-openembedded in the fido branch

### ISSUE THREAD

**Issue by carbn** [flihp/meta-measured#19]
After adding meta-openembedded/meta-networking to my bblayers.conf I encountered the following error:

```
ERROR: No recipes available for:
  /home/carbn/poky/meta-measured/networking-layer/recipes-support/strongswan/strongswan_5.3.0.bbappend
```

This is caused by a version mismatch between meta-measured and meta-openembedded. I have both layers checked out to 'fido' branch and OE has version 5.2.1 of the recipe, instead of 5.3.0.

**Comment by flihp** [comment]
Thanks for pointing this out. I really need to carve out some time to fix my autobuilder for meta-measured. Will hopefully find the cycles over the upcoming holiday.
