### ISSUE TITLE
Create jethro branch

### ISSUE THREAD

**Issue by derekstraka** [flihp/meta-measured#22]
Could we get a jethro branch at or near commit 66aca6b?  Thanks

**Comment by flihp** [comment]
Yeah @derekstraka, I guess it's time to grow up a bit if people are depending on this to do more than play around. I'll give a branch at this hash a go, probably good to front load a Krogoth branch too. Probably won't make much progress on this till the weekend though.

**Comment by flihp** [comment]
@derekstraka : Got a build with Jethro branch from that commit just now. Just want to be sure you know that Jethro will then only have TPM 1.2, not 2.0. If you're good with that I'll push. We can do 2.0 in Krogoth.

**Comment by derekstraka** [comment]
@flihp - Having TPM 1.2 for jethro will be fine with us.  Thanks for making the branch.

**Comment by flihp** [comment]
should be "done", feel free to create new issues related to this branch as needed
