### ISSUE TITLE
Create morty branch

### ISSUE THREAD

**Issue by derekstraka** [flihp/meta-measured#31]
The yocto 2.2 release (morty) has been out for a while and it would probably be beneficial to create the a branch for this version

**Comment by flihp** [comment]
Yeah I've got some house keeping to do. Sorry bout that. Am giving a talk @ ELC in a few weeks though so I've gotta get this stuff cleaned up for my talk.

**Comment by flihp** [comment]
better late than never, resolved in https://github.com/flihp/meta-measured/tree/morty
