### ISSUE TITLE
dangling grub-efi_2.00.bbappend

### ISSUE THREAD

**Issue by pohly** [flihp/meta-measured#41]
openembedded-core/meta/recipes-bsp/grub/grub-efi_2.02.bb was updated to 2.02, causing:

ERROR: No recipes available for:
  /fast/work/intel-iot-refkit/meta-measured/recipes-bsp/grub/grub-efi_2.00.bbappend

Looking at the .bbappend it seems to me that it doesn't really depend on the specific version. Perhaps grub-efi_%.bbappend would be better?

**Comment by flihp** [comment]
Hey @pohly. This was an old project gone stale. I'll be removing it. Similar future work should be tracking the patch set from the grub mailing list. I ran across this yesterday while reviving my build machine to test #40. I'll leave this issue open till it's resolved though.

**Comment by flihp** [comment]
resolved a while back, closing
