### ISSUE TITLE
tpm2.0-tools does not compile with gcc7 + OE-core master

### ISSUE THREAD

**Issue by pohly** [flihp/meta-measured#42]
Not strictly an issue with the recipe itself, but the fix has to be done in the upstream code and then in the recipe (either by backporting a fix or bumping the version), so I am filing it here. OE-core master switch to gcc7 as default, and that compiler warns (and due to -Werror, aborts) because of this:
```
| ../tpm2.0-tools/tools/tpm2_dump_capability.c: In function 'dump_tpm_capability':
| ../tpm2.0-tools/tools/tpm2_dump_capability.c:596:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
|          dump_command_attr_array (capabilities->command.commandAttributes,
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|                                   capabilities->command.count);
|                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| ../tpm2.0-tools/tools/tpm2_dump_capability.c:599:5: note: here
|      default:
|      ^~~~~~~
| ../tpm2.0-tools/tools/main.c: In function 'main':
| ../tpm2.0-tools/tools/main.c:62:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
|          fprintf (stderr,
|          ^~~~~~~~~~~~~~~~
|                   "failed to load manpage, check your environment / PATH\n");
|                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| ../tpm2.0-tools/tools/main.c:65:5: note: here
|      case 2:
|      ^~~~
```

There might be other issues, I've only quoted the one where compilation stops.

**Comment by jiazhang0** [comment]
@pohly I worked with Philip on new tpm2 resource manager so I understand his heavy workload. If you  would like, you may switch to use meta-tpm and meta-tpm2 registered in OE index page. It inherited most of tpm/tpm2 packages and closely sync up with upstream of tpm2.0-tool, tpm2.0-tss and tpm2-abrmd. Meanwhile, I highly suggest the resource manager of tpm2 should switch to using tpm2-abrmd instead of the depreciated one provided by the tpm2.0-tss. Hopefully my words don't disturb you and Philip :)

**Comment by pohly** [comment]
On Fri, 2017-07-28 at 01:58 +0000, Lans Zhang wrote:
> @pohly I worked with Philip on new tpm2 resource manager so I
> understand his heavy workload. If you would like, you may switch to
> use meta-tpm and meta-tpm2 registered in OE index page.

How is this related to meta-measured? Is it an official successor and
will @flihp contribute to it instead of maintaining meta-measured?

The other alternative is meta-tpm from the meta-security repo, which
recently became its own layer.

**Comment by jiazhang0** [comment]
@pohly on sorry I missed the context and thus misunderstood Philips's reply. He said the grub patchset is  depreciated. I wrongly think he was talking meta-measured. Forget my words.

**Comment by flihp** [comment]
think we resolved this a while back, closing
