### ISSUE TITLE
autoconf failing to build tpm2-tss, says undefined macros

### ISSUE THREAD

**Issue by pscheie** [flihp/meta-measured#60]
I'm trying to build tpm2-tss in Wind River Linux 8.  As you know, it depends on autoconf-archive-native.  We don't have that package available in our build system* so I just downloaded the autoconf-archive tar file and used the recipe for it, and it seems to build fine by itself.  In tpm2-tss.inc I changed the DEPENDS value to autoconf-archive (i.e., remove the -native part).  But when I try to configure tpm2-tss, autoreconf fails saying AC_SUBST, AS_IF, AC_MSG_ERROR, and AC_MSG_WARN in configure.in are "possibly undefined" macros.  Just to poke at it, if I comment out the DEPENDS line in tpm2-tss.inc, I get the same errors, suggesting either the problem has nothing to do with autoconf-archive or the build of tpm2-tss is not seeing whatever autoconf-archive is providing.  It may be worth noting that in the recipe for autoconf-archive, it defines BBCLASSEXTEND = "native nativesdk" so it would seem that it should be available for the tpm2-tss build (right?)

Any suggestions as to why these macros seem undefined, and how to fix it?  Thanks.

*WR says there is a autoconf-archive package in the x86_64 BSP layer, and setting --enable-board=x86-64 should pull it in.  However, we specify a different board (that of our hardware vendor) that is x86-based, but we don't seem to get the autoconf-archive package pulled in.

Peter

**Comment by flihp** [comment]
'possibly undefined' means 'I couldn't find it, but it may be included through other means' in autoconf speak. I've only ever seen this error message when macro definitions are missing so I think your analysis is correct: Whatever you've done to build the autoconf-archive recipe into your WR build environment isn't sufficient for the other recipes to use it.

**Comment by flihp** [comment]
Closing this since it's not really an issue with the recipes here.
