### ISSUE TITLE
md5sum of tboot.gz is different every build

### ISSUE THREAD

**Issue by pscheie** [flihp/meta-measured#74]
When I build tboot from the tboot-1.9.6.tar.gz file by hand, the resulting tboot.gz file is identical every time, that is, the md5sum is the same.  However, when I build it using bitbake and the OE recipe, tboot.gz is different every time.   Is this behavior expected?

This presents a problem because we have to sign tboot.gz to use it with grub.  For final releases, files needing signatures have to be copied off to disconnected machines for to get signed.  Since tboot.gz isn't really changing, I was hoping I could do it once and be done with it.  But if it changes every time we build, that means I have to figure out a process to get it signed every build even for development purposes, which would be a real pain.  I would have expected tboot.gz to be the same every build, as long as no parameters are changed.

**Comment by flihp** [comment]
Whether or not tboot supports reproducible builds is out of our control. Would be great if they did but that would have to be fixed upstream.
